import LZString from 'lz-string'

const STORAGE_KEY = 'pid_tuner_session'

// Source of the last session load — read once in App.jsx after mount
export let lastLoadSource = null

// ── Serialization ────────────────────────────────────────────────────────────

function serializePlant(p) {
  return {
    method:      p.method,
    num:         Array.from(p.num),
    den:         Array.from(p.den),
    delay:       p.delay,
    order:       p.order,
    identOrder:  p.identOrder,
    identDelay:  p.identDelay,
    // identData excluded: external binary data, may be large
  }
}

function serializeResults(r) {
  if (!r) return null
  return {
    kp:               r.kp,
    ki:               r.ki,
    kd:               r.kd,
    kpAdj:            r.kpAdj,
    kiAdj:            r.kiAdj,
    kdAdj:            r.kdAdj,
    metrics:          r.metrics   ? { ...r.metrics }              : null,
    convergence:      r.convergence ? Array.from(r.convergence)   : [],
    finalCost:        r.finalCost,
    allConstraintsMet: r.allConstraintsMet,
    statusMessage:    r.statusMessage,
    // simData  excluded: Float64Arrays, regenerated by ResultsPage
    // freqData excluded: large arrays, regenerated by ResultsPage
  }
}

export function serializeState(state) {
  return {
    plant:     serializePlant(state.plant),
    criterion: { ...state.criterion },
    optimizer: { ...state.optimizer },
    results:   serializeResults(state.results),
  }
}

// ── localStorage ─────────────────────────────────────────────────────────────

export function saveSession(state) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(serializeState(state)))
  } catch {}
}

function loadFromLocalStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? JSON.parse(raw) : null
  } catch { return null }
}

// ── URL state ────────────────────────────────────────────────────────────────

function decodeURLParam() {
  try {
    const encoded = new URLSearchParams(window.location.search).get('state')
    if (!encoded) return null
    const json = LZString.decompressFromEncodedURIComponent(encoded)
    return json ? JSON.parse(json) : null
  } catch { return null }
}

export function buildShareURL(state) {
  try {
    const encoded = LZString.compressToEncodedURIComponent(JSON.stringify(serializeState(state)))
    const base = window.location.origin + window.location.pathname
    const hash = window.location.hash || '#/'
    return `${base}?state=${encoded}${hash}`
  } catch { return null }
}

// ── Apply state to store ─────────────────────────────────────────────────────

function applyState(store, data) {
  if (!data) return false
  try {
    if (data.plant)     store.setPlant(data.plant)
    if (data.criterion) store.setCriterion(data.criterion)
    if (data.optimizer) store.setOptimizerConfig(data.optimizer)
    if (data.results)   store.setResults(data.results)
    return true
  } catch { return false }
}

// ── Entry point: called once in main.jsx before first render ─────────────────

export function loadInitialState(store) {
  // URL ?state= takes priority (shared link)
  const urlData = decodeURLParam()
  if (urlData && applyState(store, urlData)) {
    lastLoadSource = 'url'
    // Strip ?state= from URL so sharing again uses current state
    window.history.replaceState(
      null, '',
      window.location.origin + window.location.pathname + window.location.hash
    )
    return 'url'
  }
  // Fallback: localStorage auto-save
  const localData = loadFromLocalStorage()
  if (localData && applyState(store, localData)) {
    lastLoadSource = 'local'
    return 'local'
  }
  return null
}
